---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata: 
  generateName: cmusali-test-pipeline-run-
  namespace: test-rhtap-1-tenant
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
    - name: pathInRepo
      value: pipeline/hello-world.yaml
    - name: revision
      value: c2971add57044d1a95d68677ebd8a4990a0d5498
