---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata: 
  generateName: cmusali-test-pipeline-run-
  namespace: test-rhtap-1-tenant
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
    - name: pathInRepo
      value: pipeline/hello-world.yaml
    - name: revision
      value: 9a1c55972e004c46d73a6dc72533f9cb0a6c3fee
