---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata: 
  name: hello-world-pipelinerun
  namespace: test-rhtap-1-tenant
spec:
  pipelineSpec:
    tasks: 
    - name: print-hello-world
      taskSpec:
        steps:
        - name: run-echo-cmd
          image: registry.access.redhat.com/ubi9/ubi-minimal
          script: echo 'Hello World'