---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-echo
  namespace: test-rhtap-1-tenant
spec:
  steps:
  - name: run-echo-cmd
    image: registry.access.redhat.com/ubi9/ubi-minimal
    script: echo 'Hello World'
