---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: hello-world
  namespace: test-rhtap-1-tenant
spec:
  tasks: 
  - name: print-hello-world
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: master