---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: hello-world
  namespace: test-rhtap-1-tenant
spec:
  tasks: 
  - name: print-hello-world-1
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-2
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-3
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-4
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-5
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-6
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-7
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-8
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-9
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-10
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-11
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-12
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-13
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-14
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498
  - name: print-hello-world-15
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/mcharanrm/tekton-resolver-benchmarks.git
      - name: pathInRepo
        value: tasks/run-echo.yaml
      - name: revision
        value: c2971add57044d1a95d68677ebd8a4990a0d5498